-- MySQL Script generated by MySQL Workbench
-- Wed Jun 27 17:06:12 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `IdUser` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(256) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `email` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`IdUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `IdCategory` INT NOT NULL AUTO_INCREMENT,
  `CatgeoryName` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`IdCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Photo` (
  `IdPhoto` INT NOT NULL AUTO_INCREMENT,
  `IdUser` INT NOT NULL,
  `PhotoName` VARCHAR(256) NOT NULL,
  `Descr` VARCHAR(256) NOT NULL,
  `IdCategory` INT NOT NULL,
  `IsPublic` INT NOT NULL DEFAULT 0,
  `Views` INT NOT NULL DEFAULT 0,
  `FullPic` LONGBLOB NOT NULL,
  `Thumb` LONGBLOB NOT NULL,
  PRIMARY KEY (`IdPhoto`),
  INDEX `UserId_idx` (`IdUser` ASC),
  INDEX `IdCategory_idx` (`IdCategory` ASC),
  CONSTRAINT `IdUser`
    FOREIGN KEY (`IdUser`)
    REFERENCES `mydb`.`User` (`IdUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdCategory`
    FOREIGN KEY (`IdCategory`)
    REFERENCES `mydb`.`Category` (`IdCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
